input {
  tcp {
    port => 50000
    codec => json_lines
  }
}

filter {
  date {
    match => [ "timestamp", "ISO8601" ]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "krampus-logs-%{+YYYY.MM.dd}"
  }
}
