// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_status.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertDeliveryStatus = `-- name: UpsertDeliveryStatus :exec
INSERT INTO message_delivery_status (message_id, user_id, status, delivered_at, read_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(message_id, user_id)
DO UPDATE SET
    status = EXCLUDED.status,
    delivered_at = EXCLUDED.delivered_at,
    read_at = EXCLUDED.read_at,
    updated_at = NOW()
`

type UpsertDeliveryStatusParams struct {
	MessageID   string           `json:"message_id"`
	UserID      string           `json:"user_id"`
	Status      string           `json:"status"`
	DeliveredAt pgtype.Timestamp `json:"delivered_at"`
	ReadAt      pgtype.Timestamp `json:"read_at"`
}

func (q *Queries) UpsertDeliveryStatus(ctx context.Context, arg UpsertDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, upsertDeliveryStatus,
		arg.MessageID,
		arg.UserID,
		arg.Status,
		arg.DeliveredAt,
		arg.ReadAt,
	)
	return err
}
