// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dlq.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDLQMessage = `-- name: CreateDLQMessage :exec
INSERT INTO message_dlq (id, message_id, user_id, room_id, payload, reason)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateDLQMessageParams struct {
	ID        pgtype.UUID `json:"id"`
	MessageID string      `json:"message_id"`
	UserID    string      `json:"user_id"`
	RoomID    string      `json:"room_id"`
	Payload   []byte      `json:"payload"`
	Reason    string      `json:"reason"`
}

func (q *Queries) CreateDLQMessage(ctx context.Context, arg CreateDLQMessageParams) error {
	_, err := q.db.Exec(ctx, createDLQMessage,
		arg.ID,
		arg.MessageID,
		arg.UserID,
		arg.RoomID,
		arg.Payload,
		arg.Reason,
	)
	return err
}
