// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldMessages = `-- name: CleanupOldMessages :exec
DELETE FROM messages WHERE expires_at < NOW()
`

func (q *Queries) CleanupOldMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldMessages)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, type, user_id, room_id, timestamp, payload, signature, created_at
FROM messages
WHERE id = $1 LIMIT 1
`

type GetMessageRow struct {
	ID        string             `json:"id"`
	Type      string             `json:"type"`
	UserID    string             `json:"user_id"`
	RoomID    string             `json:"room_id"`
	Timestamp int64              `json:"timestamp"`
	Payload   []byte             `json:"payload"`
	Signature pgtype.Text        `json:"signature"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMessage(ctx context.Context, id string) (GetMessageRow, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.UserID,
		&i.RoomID,
		&i.Timestamp,
		&i.Payload,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}

const getReplies = `-- name: GetReplies :many
SELECT id, type, user_id, room_id, timestamp, payload, signature, version, edited_at, deleted_at, reply_to_id, forwarded_from_id, topic_id, scheduled_at, search_vector, created_at, expires_at
FROM messages
WHERE reply_to_id = $1
AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) GetReplies(ctx context.Context, replyToID pgtype.Text) ([]Message, error) {
	rows, err := q.db.Query(ctx, getReplies, replyToID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.UserID,
			&i.RoomID,
			&i.Timestamp,
			&i.Payload,
			&i.Signature,
			&i.Version,
			&i.EditedAt,
			&i.DeletedAt,
			&i.ReplyToID,
			&i.ForwardedFromID,
			&i.TopicID,
			&i.ScheduledAt,
			&i.SearchVector,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomMessages = `-- name: GetRoomMessages :many
SELECT id, type, user_id, room_id, timestamp, payload, signature, created_at
FROM messages
WHERE room_id = $1
ORDER BY timestamp DESC
LIMIT $2
`

type GetRoomMessagesParams struct {
	RoomID string `json:"room_id"`
	Limit  int32  `json:"limit"`
}

type GetRoomMessagesRow struct {
	ID        string             `json:"id"`
	Type      string             `json:"type"`
	UserID    string             `json:"user_id"`
	RoomID    string             `json:"room_id"`
	Timestamp int64              `json:"timestamp"`
	Payload   []byte             `json:"payload"`
	Signature pgtype.Text        `json:"signature"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]GetRoomMessagesRow, error) {
	rows, err := q.db.Query(ctx, getRoomMessages, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomMessagesRow{}
	for rows.Next() {
		var i GetRoomMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.UserID,
			&i.RoomID,
			&i.Timestamp,
			&i.Payload,
			&i.Signature,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveMessage = `-- name: SaveMessage :exec
INSERT INTO messages (id, type, user_id, room_id, timestamp, payload, signature, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW() + INTERVAL '60 days')
`

type SaveMessageParams struct {
	ID        string      `json:"id"`
	Type      string      `json:"type"`
	UserID    string      `json:"user_id"`
	RoomID    string      `json:"room_id"`
	Timestamp int64       `json:"timestamp"`
	Payload   []byte      `json:"payload"`
	Signature pgtype.Text `json:"signature"`
}

func (q *Queries) SaveMessage(ctx context.Context, arg SaveMessageParams) error {
	_, err := q.db.Exec(ctx, saveMessage,
		arg.ID,
		arg.Type,
		arg.UserID,
		arg.RoomID,
		arg.Timestamp,
		arg.Payload,
		arg.Signature,
	)
	return err
}

const softDelete = `-- name: SoftDelete :exec
UPDATE messages
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDelete, id)
	return err
}
