// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LoginAttempt struct {
	ID          int64              `json:"id"`
	Email       string             `json:"email"`
	Success     bool               `json:"success"`
	AttemptedAt pgtype.Timestamptz `json:"attempted_at"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
}

type Message struct {
	ID        string             `json:"id"`
	Type      string             `json:"type"`
	UserID    string             `json:"user_id"`
	RoomID    string             `json:"room_id"`
	Timestamp int64              `json:"timestamp"`
	Payload   []byte             `json:"payload"`
	Signature pgtype.Text        `json:"signature"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type MessageDeduplication struct {
	IdempotencyKey string           `json:"idempotency_key"`
	MessageID      string           `json:"message_id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type MessageDeliveryStatus struct {
	MessageID   string           `json:"message_id"`
	UserID      string           `json:"user_id"`
	Status      string           `json:"status"`
	DeliveredAt pgtype.Timestamp `json:"delivered_at"`
	ReadAt      pgtype.Timestamp `json:"read_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type MessageDlq struct {
	ID        pgtype.UUID      `json:"id"`
	MessageID string           `json:"message_id"`
	UserID    string           `json:"user_id"`
	RoomID    string           `json:"room_id"`
	Payload   []byte           `json:"payload"`
	Reason    string           `json:"reason"`
	FailedAt  pgtype.Timestamp `json:"failed_at"`
}

type MessageRetryQueue struct {
	ID          pgtype.UUID      `json:"id"`
	MessageID   string           `json:"message_id"`
	UserID      string           `json:"user_id"`
	RoomID      string           `json:"room_id"`
	Payload     []byte           `json:"payload"`
	Attempt     int32            `json:"attempt"`
	NextRetryAt pgtype.Timestamp `json:"next_retry_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID      `json:"id"`
	AggregateType string           `json:"aggregate_type"`
	AggregateID   string           `json:"aggregate_id"`
	EventType     string           `json:"event_type"`
	Payload       []byte           `json:"payload"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	PublishedAt   pgtype.Timestamp `json:"published_at"`
	RetryCount    int32            `json:"retry_count"`
	LastError     pgtype.Text      `json:"last_error"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID        string `json:"id"`
	Type      string `json:"type"`
	OwnerID   string `json:"owner_id"`
	Name      string `json:"name"`
	Members   []byte `json:"members"`
	Settings  []byte `json:"settings"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type TwoFaCode struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Attempts  pgtype.Int4        `json:"attempts"`
	IsUsed    pgtype.Bool        `json:"is_used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Firstname         string             `json:"firstname"`
	Lastname          string             `json:"lastname"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	TwoFaEnabled      pgtype.Bool        `json:"two_fa_enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	BlockedUntil      pgtype.Timestamptz `json:"blocked_until"`
	FailedAttempts    pgtype.Int4        `json:"failed_attempts"`
	LastFailedAttempt pgtype.Timestamptz `json:"last_failed_attempt"`
}
