// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replay.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMessagesAfter = `-- name: GetMessagesAfter :many
SELECT id, room_id, user_id, type, payload, timestamp, signature
FROM messages
WHERE room_id = $1
  AND timestamp > $2
ORDER BY timestamp ASC
LIMIT $3
`

type GetMessagesAfterParams struct {
	RoomID     string `json:"room_id"`
	AfterTs    int64  `json:"after_ts"`
	LimitCount int32  `json:"limit_count"`
}

type GetMessagesAfterRow struct {
	ID        string      `json:"id"`
	RoomID    string      `json:"room_id"`
	UserID    string      `json:"user_id"`
	Type      string      `json:"type"`
	Payload   []byte      `json:"payload"`
	Timestamp int64       `json:"timestamp"`
	Signature pgtype.Text `json:"signature"`
}

func (q *Queries) GetMessagesAfter(ctx context.Context, arg GetMessagesAfterParams) ([]GetMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, getMessagesAfter, arg.RoomID, arg.AfterTs, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesAfterRow{}
	for rows.Next() {
		var i GetMessagesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.Timestamp,
			&i.Signature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
