// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retry.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRetryJob = `-- name: CreateRetryJob :exec
INSERT INTO message_retry_queue (id, message_id, user_id, room_id, payload, attempt, next_retry_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateRetryJobParams struct {
	ID          pgtype.UUID      `json:"id"`
	MessageID   string           `json:"message_id"`
	UserID      string           `json:"user_id"`
	RoomID      string           `json:"room_id"`
	Payload     []byte           `json:"payload"`
	Attempt     int32            `json:"attempt"`
	NextRetryAt pgtype.Timestamp `json:"next_retry_at"`
}

func (q *Queries) CreateRetryJob(ctx context.Context, arg CreateRetryJobParams) error {
	_, err := q.db.Exec(ctx, createRetryJob,
		arg.ID,
		arg.MessageID,
		arg.UserID,
		arg.RoomID,
		arg.Payload,
		arg.Attempt,
		arg.NextRetryAt,
	)
	return err
}

const deleteRetryJob = `-- name: DeleteRetryJob :exec
DELETE FROM message_retry_queue
WHERE message_id = $1
AND user_id = $2
`

type DeleteRetryJobParams struct {
	MessageID string `json:"message_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeleteRetryJob(ctx context.Context, arg DeleteRetryJobParams) error {
	_, err := q.db.Exec(ctx, deleteRetryJob, arg.MessageID, arg.UserID)
	return err
}

const getReadyRetryJobs = `-- name: GetReadyRetryJobs :many
SELECT id, message_id, user_id, room_id, payload, attempt, next_retry_at, created_at
FROM message_retry_queue
WHERE next_retry_at <= NOW()
ORDER BY next_retry_at ASC
LIMIT $1
`

func (q *Queries) GetReadyRetryJobs(ctx context.Context, limit int32) ([]MessageRetryQueue, error) {
	rows, err := q.db.Query(ctx, getReadyRetryJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageRetryQueue{}
	for rows.Next() {
		var i MessageRetryQueue
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.RoomID,
			&i.Payload,
			&i.Attempt,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
