// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, type, owner_id, name, members, settings, created_at, updated_at, avatar
FROM rooms
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoomByID(ctx context.Context, id string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OwnerID,
		&i.Name,
		&i.Members,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
	)
	return i, err
}

const listRoomsByNamePrefix = `-- name: ListRoomsByNamePrefix :many
SELECT id, type, owner_id, name, members, settings, created_at, updated_at, avatar FROM rooms
WHERE name LIKE $1
`

func (q *Queries) ListRoomsByNamePrefix(ctx context.Context, name string) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsByNamePrefix, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OwnerID,
			&i.Name,
			&i.Members,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRooms = `-- name: ListUserRooms :many
SELECT id, type, owner_id, name, members, settings, created_at, updated_at, avatar FROM rooms
WHERE members @> $1::jsonb
`

func (q *Queries) ListUserRooms(ctx context.Context, dollar_1 []byte) ([]Room, error) {
	rows, err := q.db.Query(ctx, listUserRooms, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OwnerID,
			&i.Name,
			&i.Members,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :exec
UPDATE rooms
SET name = $2, members = $3, settings = $4, updated_at = $5, avatar = $6
WHERE id = $1
`

type UpdateRoomParams struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Members   []byte      `json:"members"`
	Settings  []byte      `json:"settings"`
	UpdatedAt int64       `json:"updated_at"`
	Avatar    pgtype.Text `json:"avatar"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) error {
	_, err := q.db.Exec(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.Members,
		arg.Settings,
		arg.UpdatedAt,
		arg.Avatar,
	)
	return err
}

const upsertRoom = `-- name: UpsertRoom :exec
INSERT INTO rooms (id, type, owner_id, name, members, settings, created_at, updated_at, avatar)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    members = EXCLUDED.members,
    settings = EXCLUDED.settings,
    updated_at = EXCLUDED.updated_at,
    avatar = EXCLUDED.avatar
`

type UpsertRoomParams struct {
	ID        string      `json:"id"`
	Type      string      `json:"type"`
	OwnerID   string      `json:"owner_id"`
	Name      string      `json:"name"`
	Members   []byte      `json:"members"`
	Settings  []byte      `json:"settings"`
	CreatedAt int64       `json:"created_at"`
	UpdatedAt int64       `json:"updated_at"`
	Avatar    pgtype.Text `json:"avatar"`
}

func (q *Queries) UpsertRoom(ctx context.Context, arg UpsertRoomParams) error {
	_, err := q.db.Exec(ctx, upsertRoom,
		arg.ID,
		arg.Type,
		arg.OwnerID,
		arg.Name,
		arg.Members,
		arg.Settings,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Avatar,
	)
	return err
}
