// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_messages.sql

package database

import (
	"context"
)

const searchMessages = `-- name: SearchMessages :many
SELECT id, type, user_id, room_id, timestamp, payload, signature, version, edited_at, deleted_at, reply_to_id, forwarded_from_id, topic_id, scheduled_at, search_vector, created_at, expires_at
FROM messages
WHERE search_vector @@ plainto_tsquery($1)
AND deleted_at IS NULL
AND (
    scheduled_at IS NULL
    OR scheduled_at <= NOW()
)
ORDER BY ts_rank(search_vector, plainto_tsquery($1)) DESC
LIMIT $2 OFFSET $3
`

type SearchMessagesParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, searchMessages, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.UserID,
			&i.RoomID,
			&i.Timestamp,
			&i.Payload,
			&i.Signature,
			&i.Version,
			&i.EditedAt,
			&i.DeletedAt,
			&i.ReplyToID,
			&i.ForwardedFromID,
			&i.TopicID,
			&i.ScheduledAt,
			&i.SearchVector,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
