// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_profile.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateProfile = `-- name: UpdateProfile :exec
UPDATE user_profiles
SET
    username = $1,
    bio = $2,
    version = version + 1
WHERE user_id = $3
AND version = $4
`

type UpdateProfileParams struct {
	Username pgtype.Text `json:"username"`
	Bio      pgtype.Text `json:"bio"`
	UserID   pgtype.UUID `json:"user_id"`
	Version  int64       `json:"version"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile,
		arg.Username,
		arg.Bio,
		arg.UserID,
		arg.Version,
	)
	return err
}
